language: go

notifications:
  email: false

go:
    - 1.10.3
    - master

before_install:
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - go get -u github.com/golang/lint/golint
    - go get gopkg.in/jarcoal/httpmock.v1

install:
  - dep ensure

script:
    - golint -set_exit_status
    - go test -v
