language: go

notifications:
  email: false

go:
    - 1.10.3
    - master

before_install:
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - go get -u github.com/golang/lint/golint
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

install:
  - dep ensure

script:
    - golint -set_exit_status
    - go test -v

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
